serve:
  endpoint: /
sources:
  - name: Healthcheck
    handler:
      openapi:
        endpoint: https://7iy892tbyb.execute-api.eu-central-1.amazonaws.com/healthcheck
        source: ./json-schemas/openapi-healthcheck.json
